### ISSUE TITLE
Found a bug in cities

### ISSUE THREAD

**Issue by mohab-sameh** [abdullahofmsa/CS442QualityProject#4]
Bug in maryoteya in cities.

### Expected Outcome:
Expecting to see zayed.

### Actual Outcome:
Found maryoteya

### Steps to reproduce:

1. Open app
2. go to cities
3. fetch all cities.

### Affected Files:
Cities.txt

### Recommendations:
Change maryoteya to zayed.

**Comment by nn-287** [comment]
@mohab-sameh  issue agreed
